#!/usr/bin/env python3
"""
Backfill WEEX AI logs for historical fills (no orders placed).

- Reads fills from WEEX history
- Uploads AI logs with orderId (stage=Execution)
- Idempotent via local SQLite
- Dry-run supported
"""

import argparse
import json
import os
import sqlite3
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List

from alphagenesis.data import WEEXClient

DEFAULT_SYMBOLS = [
    "cmt_btcusdt",
    "cmt_ethusdt",
    "cmt_solusdt",
    "cmt_dogeusdt",
    "cmt_xrpusdt",
    "cmt_adausdt",
    "cmt_bnbusdt",
    "cmt_ltcusdt",
]

EXPLANATION = (
    "AI execution log for AlphaGenesis. Trade decision generated by SDM strategy selection "
    "and risk checks; order executed on WEEX futures and later closed per system rules. "
    "This log records inputs, outputs, and execution details for audit/compliance."
)

MODEL_LABEL = "AlphaGenesis-SDM-v1"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backfill WEEX AI logs from historical fills")
    parser.add_argument("--since", default="2026-01-01", help="ISO date (YYYY-MM-DD) lower bound")
    parser.add_argument("--dry-run", action="store_true", help="Do not upload; print sample payloads")
    parser.add_argument("--limit", type=int, default=200, help="Max fills to process per symbol")
    parser.add_argument("--symbol", action="append", help="Symbol filter (can be repeated)")
    parser.add_argument("--sleep", type=float, default=0.4, help="Sleep between uploads (seconds)")
    parser.add_argument("--db", default="/opt/AlphaGenesis/tmp/ai_log_backfill.sqlite", help="Local idempotency DB")
    parser.add_argument("--evidence-dir", default="/opt/AlphaGenesis/evidence/2026-01-20_weex_evidence", help="Evidence output dir")
    return parser.parse_args()


def iso_to_ms(date_str: str) -> int:
    dt = datetime.strptime(date_str, "%Y-%m-%d").replace(tzinfo=timezone.utc)
    return int(dt.timestamp() * 1000)


def ensure_db(db_path: str) -> sqlite3.Connection:
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS uploaded_orders (
            order_id TEXT PRIMARY KEY,
            uploaded_at_ms INTEGER NOT NULL,
            payload_json TEXT NOT NULL
        )
        """
    )
    return conn


def already_uploaded(conn: sqlite3.Connection, order_id: str) -> bool:
    row = conn.execute(
        "SELECT order_id FROM uploaded_orders WHERE order_id = ?",
        (order_id,),
    ).fetchone()
    return row is not None


def record_uploaded(conn: sqlite3.Connection, order_id: str, payload: Dict[str, Any]) -> None:
    conn.execute(
        "INSERT OR REPLACE INTO uploaded_orders (order_id, uploaded_at_ms, payload_json) VALUES (?, ?, ?)",
        (order_id, int(time.time() * 1000), json.dumps(payload, ensure_ascii=True, default=str)),
    )
    conn.commit()


def normalize_fills(resp: Any) -> List[Dict[str, Any]]:
    if isinstance(resp, list):
        return resp
    if isinstance(resp, dict):
        data = resp.get("data", resp)
        if isinstance(data, list):
            return data
        if isinstance(data, dict):
            for key in ("list", "records", "data"):
                if isinstance(data.get(key), list):
                    return data.get(key)
    return []


def fetch_fills(client: WEEXClient, symbol: str, limit: int) -> List[Dict[str, Any]]:
    resp = client.get_trade_fills(symbol=symbol, page_size=limit)
    fills = normalize_fills(resp)
    return fills[:limit]


def build_payload(fill: Dict[str, Any]) -> Dict[str, Any]:
    order_id = fill.get("orderId") or fill.get("order_id")
    input_payload = {
        "symbol": fill.get("symbol"),
        "orderId": order_id,
        "side": fill.get("orderSide") or fill.get("legacyOrdeDirection"),
        "positionSide": fill.get("positionSide"),
        "fillSize": fill.get("fillSize"),
        "fillValue": fill.get("fillValue"),
        "direction": fill.get("direction"),
        "createdTime": fill.get("createdTime"),
    }
    output_payload = {
        "orderId": order_id,
        "fillFee": fill.get("fillFee"),
        "realizePnl": fill.get("realizePnl"),
        "liquidateFee": fill.get("liquidateFee"),
        "contractVal": fill.get("contractVal"),
        "tradeId": fill.get("tradeId"),
    }
    payload = {
        "orderId": order_id,
        "stage": "Execution",
        "model": MODEL_LABEL,
        "input": input_payload,
        "output": output_payload,
        "explanation": EXPLANATION[:1000],
    }
    return payload


def main() -> int:
    args = parse_args()
    since_ms = iso_to_ms(args.since)
    symbols = args.symbol if args.symbol else DEFAULT_SYMBOLS

    evidence_dir = Path(args.evidence_dir)
    evidence_dir.mkdir(parents=True, exist_ok=True)

    client = WEEXClient()
    conn = ensure_db(args.db)

    report = {
        "since": args.since,
        "symbols": symbols,
        "dry_run": args.dry_run,
        "limit_per_symbol": args.limit,
        "sleep": args.sleep,
        "total_fills": 0,
        "eligible_orders": 0,
        "uploaded": 0,
        "skipped_existing": 0,
        "errors": 0,
        "samples": [],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }

    for symbol in symbols:
        fills = fetch_fills(client, symbol, args.limit)
        if not fills:
            continue
        filtered = [f for f in fills if int(f.get("createdTime", 0) or 0) >= since_ms]
        report["total_fills"] += len(filtered)

        for fill in filtered:
            order_id = fill.get("orderId") or fill.get("order_id")
            if not order_id:
                continue
            report["eligible_orders"] += 1
            if already_uploaded(conn, str(order_id)):
                report["skipped_existing"] += 1
                continue

            payload = build_payload(fill)
            if args.dry_run:
                report["samples"].append(payload)
                continue

            try:
                resp = client.upload_ai_log(payload)
                code = resp.get("code") if isinstance(resp, dict) else None
                if code == "00000":
                    report["uploaded"] += 1
                    record_uploaded(conn, str(order_id), payload)
                else:
                    report["errors"] += 1
            except Exception:
                report["errors"] += 1

            time.sleep(args.sleep)

    if len(report["samples"]) > 3:
        report["samples"] = report["samples"][:3]

    report_path = evidence_dir / "backfill_report.json"
    summary_path = evidence_dir / "backfill_summary.txt"

    report_path.write_text(json.dumps(report, indent=2))
    summary_lines = [
        f"since={report['since']}",
        f"symbols={','.join(report['symbols'])}",
        f"dry_run={report['dry_run']}",
        f"limit_per_symbol={report['limit_per_symbol']}",
        f"total_fills={report['total_fills']}",
        f"eligible_orders={report['eligible_orders']}",
        f"uploaded={report['uploaded']}",
        f"skipped_existing={report['skipped_existing']}",
        f"errors={report['errors']}",
    ]
    summary_path.write_text("\n".join(summary_lines) + "\n")

    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
